name: Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
